#!/bin/sh
set -e
cargo fmt
cargo clippy --fix --allow-staged --allow-dirty --all-targets --all-features -- -D warnings -W clippy::pedantic -W clippy::nursery -W clippy::cargo
git add -u
cargo test --all-features
cargo deny check
